# Matrix in NumPy

In [1]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

print(A)

[[1 2]
 [3 4]]


# Matrix Addition
Shape same honi chahiye

In [2]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A + B)

[[ 6  8]
 [10 12]]


# Matrix Multiplication (Dot Product)
(row × column)

In [3]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [5]:
A @ B # shorthand property

array([[19, 22],
       [43, 50]])

# Transpose (Rows ↔ Columns)

In [6]:
A = np.array([[1,2,3],
              [4,5,6]])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


# Seed (important for ML experiments)

In [19]:
import numpy as np
np.random.seed(3)
np.random.rand(3)

array([0.5507979 , 0.70814782, 0.29090474])

# Practice (Very Important)

- 2×2 matrix banao

- Do matrices add karo

- Dot product karo

- Transpose find karo

- Random 3×3 matrix generate karo