# numpy in python

In [2]:
import numpy as np

Adventages of numpy array over python list:
- consumes less memory
- fast as compared to python list
- Convinient to use

In [5]:
%timeit np.array([1,2,3,4])

890 ns ± 17.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
%timeit a = [1,2,3,4]

74.5 ns ± 2.75 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [8]:
a = list(range(1000000))

%timeit [x * 2 for x in a]

92.9 ms ± 2.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [1]:
import numpy as np

a = np.arange(1000000)

%timeit a * 2
print(a)

5.5 ms ± 59.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
[     0      1      2 ... 999997 999998 999999]


# Creating numpy array

In [10]:
x = [1,2,3,4] # list
y = np.array(x)

In [11]:
y

array([1, 2, 3, 4])

In [12]:
type(y)

numpy.ndarray

# Built-in Methods se Arrays

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.arange(1, 10, 2) 

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0, 10, 5) # Matlab 0 se 10 tak 5 equal numbers.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
np.empty(10)

array([            nan,             nan,             nan, 7.74681715e-304,
       7.74860419e-304, 7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
       7.74860419e-304, 2.13031734e-314])

# Random Arrays

In [7]:
np.random.rand(5) # 0 se 1 ke beech random numbers.

array([0.2735762 , 0.09205482, 0.56465915, 0.18873808, 0.31264766])

In [8]:
import numpy as np

np.random.seed()   # Seed set karo
numbers = np.random.rand(5)   # 0 se 1 ke beech 5 random numbers
print(numbers)

[0.60232559 0.27605141 0.20077886 0.59792315 0.73632275]


In [23]:
np.random.randn(5) # generate a random value close to zero

array([ 0.41360876,  0.56935548,  0.40462752, -1.49024983,  1.68813101])

In [25]:
np.random.ranf(5) # 0 se 1 k darmiyan ho gi magar floating point ma ho gi

array([0.22859553, 0.353881  , 0.8315888 , 0.35802243, 0.46243827])

In [28]:
np.random.randint(5,10,5) # (min,max,no. in an array)

array([6, 5, 9, 6, 6], dtype=int32)

# Dimensions in Numpy Array

# 1D Array

In [35]:
x = [1,2,3,4] # list
y = np.array(x)
print(y.ndim)
y

1


array([1, 2, 3, 4])

# 2D Array

In [36]:
x = [[1,2,3,4],[1,2,3,4]] # list
z = np.array(x)
print(z.ndim)
z

2


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 3D Array

In [39]:
x = [[[1,2,3,4],[1,2,3,4],[1,2,3,4]]] # list
w = np.array(x)
print(w.ndim)
w

3


array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

# nD Array

In [3]:
r = [[[1,2,3,4],[1,2,3,4],[1,2,3,4]]] # list
q = np.array(r,ndmin=10 )
print(q.ndim)
q

10


array([[[[[[[[[[1, 2, 3, 4],
               [1, 2, 3, 4],
               [1, 2, 3, 4]]]]]]]]]])

In [6]:
t = [1,2,3,4]
arr = np.array(t,ndmin=3)
print(arr.ndim)
arr

3


array([[[1, 2, 3, 4]]])

# Array Attributes and Methods

In [10]:
arr = np.array([[10, 20, 30, 40],[10,20,30,40]])
arr

array([[10, 20, 30, 40],
       [10, 20, 30, 40]])

In [9]:
arr.shape

(2, 4)

In [14]:
arr.dtype # Tells us the data type

dtype('int64')

In [13]:
arr.size # Total elements

8

In [16]:
arr.ndim # Tells us the dimensions of the array

2

In [21]:
arr.max()

np.int64(40)

In [19]:
arr.min()

np.int64(10)

In [22]:
arr.argmax()

np.int64(3)

In [23]:
arr.argmin()

np.int64(0)

In [28]:
a = [[1,2,3,4],[1,2,3,4]] # 2 rows 4 columns
y = np.array(a)
print(y)
print(y.ndim)
# total elements 2 *4 = 8

[[1 2 3 4]
 [1 2 3 4]]
2


In [29]:
y.reshape(2, 3) 
# Reshape rule total elements same rahna chaheya

ValueError: cannot reshape array of size 8 into shape (2,3)

In [30]:
y.reshape(4, 2) 

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

# Operations on Arrays

##### Copying Array

In [31]:
a = np.array([1,2,3])
b = a.copy()

In [32]:
b

array([1, 2, 3])

##### Append

In [34]:
np.append(a, 4) # last per add hota hy element

array([1, 2, 3, 4])

##### Insert

In [35]:
np.insert(a, 1, 100) # Index 1 par value add.

array([  1, 100,   2,   3])

##### Sorting

In [36]:
np.sort(a)

array([1, 2, 3])

##### Delete / Remove

In [39]:
np.delete(a, 1) # index per remove krta hy

array([1, 3])

##### Combining Arrays (Concatenate)

In [40]:
a = np.array([1,2])
b = np.array([3,4])

np.concatenate((a,b))

array([1, 2, 3, 4])

##### Splitting Arrays

In [43]:
arr = np.array([1,2,3,4])

np.split(arr, 2)

[array([1, 2]), array([3, 4])]

## Practice Questions (Very Important)

- Python list se NumPy array banao

- arange() se 1–20 tak array banao

- reshape() use karke 2×3 matrix banao

- max aur argmax find karo

- do arrays concatenate karo